//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baitaplonweb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyKhoaHoc
    {
        public int DangKyID { get; set; }
        public int NguoiDangKyID { get; set; }
        public int KhoaHocID { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
    
        public virtual KhoaHoc KhoaHoc { get; set; }
        public virtual NguoiDangKy NguoiDangKy { get; set; }
    }
}
